backend:
  name: github
  repo: mehrad77/Jourlog
site_url: https://jourlog.xyz
logo_url: https://jourlog.xyz/assets/Jourlog.svg
publish_mode: editorial_workflow
media_folder: static/assets/bg
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: blog
    path: '{{year}}-{{month}}/{{slug}}'
    preview_path: 'blog/{{slug}}'
    create: true
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
        pattern: ['.{5,}', 'Must have at least 5 characters']
      - label: 'Date'
        name: date
        widget: string
        # dateFormat: 'YYYY-MM-DD'
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'blog'
      - label: 'Direction'
        name: 'dir'
        default: ['ltr']
        widget: 'select'
        options: ['rtl', 'ltr']
      - label: 'Category'
        name: 'category'
        default: ['English Posts']
        widget: 'select'
        options: ['English Posts', 'Farsi Posts']
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        field: { label: 'Tag', name: 'tag', widget: string }
      - label: 'Featured Image'
        name: 'banner'
        widget: 'image'
        required: false
      - label: 'Excerpt'
        name: 'excerpt'
        widget: 'markdown'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
